# https://vector.dev/docs/reference/configuration/sources/docker_logs/#examples-dummy-logs
[sources.my_source_id]
type = "docker_logs"
include_images = [ "public.ecr.aws/toricls/everlasting-hey-yo" ]

# https://vector.dev/docs/reference/configuration/sinks/file/
